export const adminNavLinks = [
  { href: "/admin", label: "Overview" },
  { href: "/admin/billing", label: "Billing" },
  { href: "/admin/branches", label: "Branches" },
  { href: "/admin/crm", label: "Lead CRM" },
  { href: "/admin/diet-planner", label: "Diet planner" },
  { href: "/admin/inventory", label: "Inventory" },
  { href: "/admin/progress", label: "Progress" },
  { href: "/admin/reminders", label: "Reminders" },
  { href: "/admin/reports", label: "Reports" },
  { href: "/admin/users", label: "Users" },
  { href: "/admin/attendance", label: "Attendance" },
  { href: "/admin/form-responses", label: "Form responses" },
  { href: "/admin/exercises", label: "Exercise library" },
  { href: "/admin/plans", label: "Workout plans" },
  { href: "/admin/memberships", label: "Memberships" },
  { href: "/admin/schedule", label: "Schedule" },
  { href: "/admin/data-tools", label: "Data tools" },
];
