import { AppData } from "@/lib/types";

export const mockData: AppData = {
  profiles: [
    {
      id: "member-1",
      fullName: "Aarav Mehta",
      email: "aarav@gymflow.test",
      phone: "+91 98765 43210",
      role: "member",
      fitnessGoal: "Lean muscle gain",
      branch: "Indore Central",
      joinedOn: "2026-01-05",
    },
    {
      id: "trainer-1",
      fullName: "Naina Kapoor",
      email: "naina@gymflow.test",
      phone: "+91 98765 43333",
      role: "trainer",
      fitnessGoal: "Coach performance training",
      branch: "Indore Central",
      joinedOn: "2025-09-11",
    },
    {
      id: "admin-1",
      fullName: "Yogesh Kukadiya",
      email: "yogeshkukadiya92@gmail.con",
      phone: "+91 98765 44444",
      role: "admin",
      fitnessGoal: "Operations oversight",
      branch: "Indore Central",
      joinedOn: "2025-08-01",
    },
    {
      id: "member-2",
      fullName: "Diya Patel",
      email: "diya@gymflow.test",
      phone: "+91 98765 45555",
      role: "member",
      fitnessGoal: "Fat loss and consistency",
      branch: "Indore Central",
      joinedOn: "2026-01-22",
    },
    {
      id: "member-3",
      fullName: "Kabir Shah",
      email: "kabir@gymflow.test",
      phone: "+91 98765 46666",
      role: "member",
      fitnessGoal: "Mobility and core strength",
      branch: "Indore Central",
      joinedOn: "2026-02-03",
    },
  ],
  userPermissions: [],
  gymBranches: [
    {
      id: "indore-central",
      name: "Indore Central",
      city: "Indore",
      address: "Vijay Nagar, Indore",
      managerName: "Yogesh Kukadiya",
      phone: "+91 98765 44444",
      kind: "Physical",
    },
    {
      id: "palasia-studio",
      name: "Palasia Studio",
      city: "Indore",
      address: "Palasia Square, Indore",
      managerName: "Naina Kapoor",
      phone: "+91 98765 43333",
      kind: "Physical",
    },
    {
      id: "online-live",
      name: "Online Live Studio",
      city: "Remote",
      address: "Zoom based branch",
      managerName: "Yogesh Kukadiya",
      phone: "+91 98765 44444",
      kind: "Online",
    },
  ],
  branchVisits: [
    {
      id: "visit-1",
      memberId: "member-1",
      branchId: "indore-central",
      visitDate: "2026-03-02",
      source: "Membership",
      note: "Primary strength training branch.",
    },
    {
      id: "visit-2",
      memberId: "member-1",
      branchId: "online-live",
      visitDate: "2026-03-18",
      source: "Attendance",
      note: "Joined online workshop batch.",
    },
    {
      id: "visit-3",
      memberId: "member-2",
      branchId: "indore-central",
      visitDate: "2026-03-05",
      source: "Membership",
      note: "Workshop monthly membership base branch.",
    },
    {
      id: "visit-4",
      memberId: "member-2",
      branchId: "palasia-studio",
      visitDate: "2026-03-21",
      source: "Walk-in",
      note: "Visited evening yoga session at Palasia branch.",
    },
    {
      id: "visit-5",
      memberId: "member-3",
      branchId: "online-live",
      visitDate: "2026-03-14",
      source: "Attendance",
      note: "Core stability online class attendance.",
    },
  ],
  memberships: [
    {
      id: "membership-1",
      memberId: "member-1",
      planName: "Elite Quarterly",
      status: "Active",
      startDate: "2026-01-05",
      renewalDate: "2026-04-05",
      billingCycle: "Quarterly",
      amountInr: 7500,
      paymentStatus: "Paid",
      lastPaymentDate: "2026-01-05",
      nextInvoiceDate: "2026-04-01",
      paymentMethod: "UPI",
      outstandingAmountInr: 0,
    },
    {
      id: "membership-2",
      memberId: "member-2",
      planName: "Workshop Monthly",
      status: "Active",
      startDate: "2026-02-01",
      renewalDate: "2026-04-01",
      billingCycle: "Monthly",
      amountInr: 3200,
      paymentStatus: "Pending",
      lastPaymentDate: "2026-02-28",
      nextInvoiceDate: "2026-03-28",
      paymentMethod: "Bank Transfer",
      outstandingAmountInr: 3200,
    },
    {
      id: "membership-3",
      memberId: "member-3",
      planName: "Workshop Monthly",
      status: "Active",
      startDate: "2026-02-03",
      renewalDate: "2026-04-03",
      billingCycle: "Monthly",
      amountInr: 3200,
      paymentStatus: "Overdue",
      lastPaymentDate: "2026-02-03",
      nextInvoiceDate: "2026-03-24",
      paymentMethod: "Cash",
      outstandingAmountInr: 3200,
    },
  ],
  invoices: [
    {
      id: "invoice-1",
      membershipId: "membership-1",
      memberId: "member-1",
      invoiceNumber: "GF-2026-001",
      issuedOn: "2026-01-05",
      dueOn: "2026-01-05",
      amountInr: 7500,
      status: "Paid",
      paidOn: "2026-01-05",
      paymentMethod: "UPI",
    },
    {
      id: "invoice-2",
      membershipId: "membership-2",
      memberId: "member-2",
      invoiceNumber: "GF-2026-014",
      issuedOn: "2026-03-01",
      dueOn: "2026-03-28",
      amountInr: 3200,
      status: "Pending",
      paymentMethod: "Bank Transfer",
    },
    {
      id: "invoice-3",
      membershipId: "membership-3",
      memberId: "member-3",
      invoiceNumber: "GF-2026-017",
      issuedOn: "2026-03-01",
      dueOn: "2026-03-24",
      amountInr: 3200,
      status: "Overdue",
      paymentMethod: "Cash",
    },
    {
      id: "invoice-4",
      membershipId: "membership-2",
      memberId: "member-2",
      invoiceNumber: "GF-2026-009",
      issuedOn: "2026-02-01",
      dueOn: "2026-02-28",
      amountInr: 3200,
      status: "Paid",
      paidOn: "2026-02-28",
      paymentMethod: "Bank Transfer",
    },
  ],
  inventoryItems: [
    {
      id: "inventory-1",
      name: "Whey Protein Isolate",
      category: "Protein",
      supplementType: "Whey isolate",
      brand: "MuscleForge",
      flavor: "Chocolate",
      supplierName: "Fit Supply Hub",
      sku: "MF-WHEY-1KG",
      batchCode: "WPI-2401-A",
      unitSize: "1 kg tub",
      expiryDate: "2027-01-15",
      stockUnits: 18,
      reorderLevel: 8,
      costPriceInr: 1550,
      sellingPriceInr: 2199,
      status: "In Stock",
    },
    {
      id: "inventory-2",
      name: "Mass Gainer",
      category: "Supplement",
      supplementType: "Mass gainer",
      brand: "StrongFuel",
      flavor: "Cookies and cream",
      supplierName: "Power Nutrition Traders",
      sku: "SF-GAIN-3KG",
      batchCode: "MG-2312-C",
      unitSize: "3 kg bag",
      expiryDate: "2026-12-30",
      stockUnits: 6,
      reorderLevel: 6,
      costPriceInr: 1800,
      sellingPriceInr: 2599,
      status: "Low Stock",
    },
    {
      id: "inventory-3",
      name: "Peanut Butter Protein Bar",
      category: "Snack",
      supplementType: "Protein bar",
      brand: "FitBite",
      flavor: "Peanut butter",
      supplierName: "Urban Wellness Foods",
      sku: "FB-BAR-BOX",
      batchCode: "PBAR-2402-B",
      unitSize: "12 bar box",
      expiryDate: "2026-09-18",
      stockUnits: 0,
      reorderLevel: 5,
      costPriceInr: 420,
      sellingPriceInr: 699,
      status: "Out of Stock",
    },
  ],
  inventorySales: [
    {
      id: "sale-1",
      itemId: "inventory-1",
      soldOn: "2026-03-21",
      quantity: 2,
      totalAmountInr: 4398,
      customerName: "Aarav Mehta",
      paymentMethod: "UPI",
    },
    {
      id: "sale-2",
      itemId: "inventory-2",
      soldOn: "2026-03-24",
      quantity: 1,
      totalAmountInr: 2599,
      customerName: "Diya Patel",
      paymentMethod: "Cash",
    },
  ],
  exercises: [
    {
      id: "exercise-1",
      name: "Barbell Back Squat",
      category: "Strength",
      difficulty: "Intermediate",
      primaryMuscle: "Quads",
      equipment: "Barbell",
      mediaType: "video",
      mediaUrl: "https://www.youtube.com/watch?v=ultWZbUMPL8",
      cues: ["Brace the core", "Drive knees out", "Keep chest tall"],
    },
    {
      id: "exercise-2",
      name: "Romanian Deadlift",
      category: "Strength",
      difficulty: "Intermediate",
      primaryMuscle: "Hamstrings",
      equipment: "Barbell",
      mediaType: "video",
      mediaUrl: "https://www.youtube.com/watch?v=2SHsk9AzdjA",
      cues: ["Push hips back", "Soft knees", "Keep bar close"],
    },
    {
      id: "exercise-3",
      name: "Walking Lunges",
      category: "Conditioning",
      difficulty: "Beginner",
      primaryMuscle: "Glutes",
      equipment: "Dumbbells",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438",
      cues: ["Long stride", "Front heel planted", "Stay upright"],
    },
    {
      id: "exercise-4",
      name: "Push-Up",
      category: "Bodyweight",
      difficulty: "Beginner",
      primaryMuscle: "Chest",
      equipment: "None",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b",
      cues: ["Straight line body", "Elbows 45 degrees", "Full lockout"],
    },
  ],
  workoutPlans: [
    {
      id: "plan-1",
      name: "Lower Body Power",
      goal: "Build lower-body strength and work capacity",
      coach: "Naina Kapoor",
      split: "4-day split",
      durationWeeks: 6,
      exercises: [
        {
          id: "plan-exercise-1",
          exerciseId: "exercise-1",
          sets: 5,
          reps: "5",
          restSeconds: 120,
          notes: "Increase load when all sets feel controlled.",
        },
        {
          id: "plan-exercise-2",
          exerciseId: "exercise-2",
          sets: 4,
          reps: "8",
          restSeconds: 90,
          notes: "Pause two seconds at the bottom range.",
        },
        {
          id: "plan-exercise-3",
          exerciseId: "exercise-3",
          sets: 3,
          reps: "12 each leg",
          restSeconds: 60,
          notes: "Focus on balance and consistent step length.",
        },
      ],
    },
    {
      id: "plan-2",
      name: "Upper Body Foundation",
      goal: "Improve pressing strength and control",
      coach: "Naina Kapoor",
      split: "3-day split",
      durationWeeks: 4,
      exercises: [
        {
          id: "plan-exercise-4",
          exerciseId: "exercise-4",
          sets: 4,
          reps: "12",
          restSeconds: 45,
          notes: "Elevate hands if form breaks down.",
        },
      ],
    },
  ],
  assignments: [
    {
      id: "assignment-1",
      planId: "plan-1",
      memberId: "member-1",
      startDate: "2026-03-10",
      status: "Active",
    },
  ],
  workoutLogs: [
    {
      id: "log-1",
      memberId: "member-1",
      exerciseId: "exercise-1",
      date: "2026-03-12",
      setsCompleted: 5,
      repsCompleted: "5/5/5/5/5",
      weightKg: 72.5,
      notes: "Last set was challenging but clean.",
    },
    {
      id: "log-2",
      memberId: "member-1",
      exerciseId: "exercise-2",
      date: "2026-03-12",
      setsCompleted: 4,
      repsCompleted: "8/8/8/8",
      weightKg: 55,
      notes: "Controlled tempo felt much better this week.",
    },
  ],
  progressCheckIns: [
    {
      id: "progress-1",
      memberId: "member-1",
      recordedOn: "2026-02-10",
      weightKg: 78.4,
      waistCm: 86,
      hipsCm: 96,
      chestCm: 101,
      thighCm: 57,
      coachNote:
        "Strength is improving. Keep protein high and stay consistent with recovery sleep.",
      energyLevel: "Medium",
    },
    {
      id: "progress-2",
      memberId: "member-1",
      recordedOn: "2026-03-10",
      weightKg: 76.8,
      waistCm: 83,
      hipsCm: 95,
      chestCm: 102,
      thighCm: 58,
      coachNote:
        "Great visual recomposition. Lower waist and stronger squat mechanics this month.",
      energyLevel: "High",
    },
    {
      id: "progress-3",
      memberId: "member-2",
      recordedOn: "2026-03-08",
      weightKg: 69.2,
      waistCm: 81,
      hipsCm: 101,
      chestCm: 93,
      thighCm: 55,
      coachNote:
        "Attendance is helping. Keep the morning mobility classes locked in.",
      energyLevel: "Medium",
    },
    {
      id: "progress-4",
      memberId: "member-3",
      recordedOn: "2026-03-12",
      weightKg: 74.6,
      waistCm: 88,
      hipsCm: 98,
      chestCm: 99,
      thighCm: 56,
      coachNote:
        "Mobility is improving, but class consistency needs attention.",
      energyLevel: "Low",
    },
  ],
  progressPhotos: [
    {
      id: "photo-1",
      memberId: "member-1",
      recordedOn: "2026-02-10",
      label: "Front check-in",
      imageUrl:
        "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=900&q=80",
      note: "Start of current body recomposition block.",
    },
    {
      id: "photo-2",
      memberId: "member-1",
      recordedOn: "2026-03-10",
      label: "Front check-in",
      imageUrl:
        "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=900&q=80",
      note: "Visible waist reduction and improved posture after four weeks.",
    },
    {
      id: "photo-3",
      memberId: "member-2",
      recordedOn: "2026-03-08",
      label: "Mobility check-in",
      imageUrl:
        "https://images.unsplash.com/photo-1518310383802-640c2de311b2?auto=format&fit=crop&w=900&q=80",
      note: "Used to compare shoulder and hip mobility over time.",
    },
  ],
  sessions: [
    {
      id: "session-1",
      title: "Online Workshop Kickoff",
      coach: "Naina Kapoor",
      day: "Monday",
      time: "07:00 AM",
      capacity: 30,
      room: "Zoom Room A",
      branchId: "online-live",
      zoomLink: "https://zoom.us/j/12345678901",
    },
    {
      id: "session-2",
      title: "Fat Loss Mobility Flow",
      coach: "Naina Kapoor",
      day: "Tuesday",
      time: "07:00 AM",
      capacity: 30,
      room: "Zoom Room A",
      branchId: "online-live",
      zoomLink: "https://zoom.us/j/12345678902",
    },
    {
      id: "session-3",
      title: "Core Stability Lab",
      coach: "Naina Kapoor",
      day: "Wednesday",
      time: "07:00 AM",
      capacity: 30,
      room: "Zoom Room B",
      branchId: "online-live",
      zoomLink: "https://zoom.us/j/12345678903",
    },
    {
      id: "session-4",
      title: "Strength Technique Reset",
      coach: "Ritvik Jain",
      day: "Thursday",
      time: "07:00 AM",
      capacity: 24,
      room: "Zoom Room B",
      branchId: "palasia-studio",
      zoomLink: "https://zoom.us/j/12345678904",
    },
    {
      id: "session-5",
      title: "Weekly Progress Review",
      coach: "Naina Kapoor",
      day: "Saturday",
      time: "09:00 AM",
      capacity: 30,
      room: "Zoom Room A",
      branchId: "indore-central",
      zoomLink: "https://zoom.us/j/12345678905",
    },
  ],
  attendance: [
    {
      id: "attendance-1",
      sessionId: "session-1",
      memberId: "member-1",
      status: "Checked In",
    },
    {
      id: "attendance-2",
      sessionId: "session-1",
      memberId: "member-2",
      status: "Booked",
    },
    {
      id: "attendance-3",
      sessionId: "session-1",
      memberId: "member-3",
      status: "Missed",
    },
    {
      id: "attendance-4",
      sessionId: "session-2",
      memberId: "member-1",
      status: "Booked",
    },
    {
      id: "attendance-5",
      sessionId: "session-2",
      memberId: "member-2",
      status: "Checked In",
    },
    {
      id: "attendance-6",
      sessionId: "session-3",
      memberId: "member-3",
      status: "Booked",
    },
    {
      id: "attendance-7",
      sessionId: "session-4",
      memberId: "member-1",
      status: "Booked",
    },
    {
      id: "attendance-8",
      sessionId: "session-5",
      memberId: "member-2",
      status: "Booked",
    },
  ],
};
